version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    container_name: redis-socket
    ports:
      - "6379:6379"
    networks:
      - socket-networks
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - socket-networks
networks:
  socket-networks:
    driver: bridge
